### ISSUE TITLE
asking training dataset

### ISSUE THREAD

**Issue by chenjiachengzzz** [yanzq95/SGNet#1]
您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛

**Comment by yanzq95** [comment]
> 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛

你好，NYU-v2数据集可以参考：[DKN] https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR] https://github.com/lingzhi96/RGB-D-D-Dataset； Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/

**Comment by chenjiachengzzz** [comment]
> > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> 
> 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/

非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎

**Comment by yanzq95** [comment]
> > > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> > 
> > 
> > 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/
> 
> 非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎

可以再尝试一下从下面这个网盘链接下载
链接：https://pan.baidu.com/s/1kvPoZuJqG5G9x6MDHwnPFQ 
提取码：dlp0

**Comment by chenjiachengzzz** [comment]
> > > > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> > > 
> > > 
> > > 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/
> > 
> > 
> > 非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎
> 
> 可以再尝试一下从下面这个网盘链接下载 链接：https://pan.baidu.com/s/1kvPoZuJqG5G9x6MDHwnPFQ 提取码：dlp0

真的万分感谢您的帮助，您人也太好啦！

**Comment by gkuberreddy** [comment]
> > > > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> > > 
> > > 
> > > 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/
> > 
> > 
> > 非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎
> 
> 可以再尝试一下从下面这个网盘链接下载 链接：https://pan.baidu.com/s/1kvPoZuJqG5G9x6MDHwnPFQ 提取码：dlp0

Hi, Thanks for the great work. can you please share the google drive link for NYv2 datasets (or) let me know if I can download from baidu link you have provided without baidunetdisk app? Since It's asking me to download netdisk app first!?

Any help would be appreciated. Thanks.

**Comment by yanzq95** [comment]
> > > > > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> > > > 
> > > > 
> > > > 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/
> > > 
> > > 
> > > 非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎
> > 
> > 
> > 可以再尝试一下从下面这个网盘链接下载 链接：https://pan.baidu.com/s/1kvPoZuJqG5G9x6MDHwnPFQ 提取码：dlp0
> 
> Hi, Thanks for the great work. can you please share the google drive link for NYv2 datasets (or) let me know if I can download from baidu link you have provided without baidunetdisk app? Since It's asking me to download netdisk app first!?
> 
> Any help would be appreciated. Thanks.

The NYU-v2 dataset is available for download from the Google Drive link provided below: https://drive.google.com/file/d/1osYRaDfMYuyiTkJwDbKl3kHwyevDLsZf/view?usp=sharing

**Comment by gkuberreddy** [comment]
> > > > > > 您好，您的工作非常棒，对我很有启发，我是刚开始从事这个方向，您能提供您使用的数据集嘛
> > > > > 
> > > > > 
> > > > > 你好，NYU-v2数据集可以参考：[DKN] [https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file；RGB-D-D数据集可以参考：[FDSR]](https://github.com/cvlab-yonsei/dkn?tab=readme-ov-file%EF%BC%9BRGB-D-D%E6%95%B0%E6%8D%AE%E9%9B%86%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%EF%BC%9A%5BFDSR%5D) [https://github.com/lingzhi96/RGB-D-D-Dataset；](https://github.com/lingzhi96/RGB-D-D-Dataset%EF%BC%9B) Middlebury & Lu数据集可以参考：https://web.cecs.pdx.edu/~fliu/project/depth-enhance/
> > > > 
> > > > 
> > > > 非常感谢您的及时回复。根据您的链接，我发现DKN提供的下载链接好像已经失效了哎
> > > 
> > > 
> > > 可以再尝试一下从下面这个网盘链接下载 链接：https://pan.baidu.com/s/1kvPoZuJqG5G9x6MDHwnPFQ 提取码：dlp0
> > 
> > 
> > Hi, Thanks for the great work. can you please share the google drive link for NYv2 datasets (or) let me know if I can download from baidu link you have provided without baidunetdisk app? Since It's asking me to download netdisk app first!?
> > Any help would be appreciated. Thanks.
> 
> The NYU-v2 dataset is available for download from the Google Drive link provided below: https://drive.google.com/file/d/1osYRaDfMYuyiTkJwDbKl3kHwyevDLsZf/view?usp=sharing

Thank you for the quick response. Cheers 👍
