### ISSUE TITLE
Question about RMSE

### ISSUE THREAD

**Issue by PhuTran1005** [yanzq95/SGNet#11]
First, thank you very much for sharing a great work.
I try to run your code, but i don't understand the function to calculate rmse on RGB-D-D dataset. Why does it divide by 10.0?
Can you answer my simple question?
Thanks.
![image](https://github.com/yanzq95/SGNet/assets/79369740/6d70cff8-1964-436f-bcf2-44753e7a3f47)

**Comment by yanzq95** [comment]
We follow the settings from previous work, and calculate the RMSE in centimeters by dividing by 10.

**Comment by PhuTran1005** [comment]
Thank you for your quick reply. I understood.
