### ISSUE TITLE
关于GPU

### ISSUE THREAD

**Issue by VMC-Lab-Chen** [yanzq95/SGNet#14]
非常感觉作者杰出的工作，我是刚入门这个方向的新人，目前我手上能用的只有一张4090显卡，我想请问一下1张4090能否满足复现您代码的需求？

**Comment by yanzq95** [comment]
没问题的。代码是单卡版本的，NYU-v2在4090上训一次大概需要30小时

**Comment by VMC-Lab-Chen** [comment]
好的感谢答复，可以再请问一下RGB-D-D、Middlebury数据集的训练时间吗？

**Comment by yanzq95** [comment]
RGB-D-D也差不多30h   其他合成数据，基本上是在nyu上训，然后直接在该数据集上测试

**Comment by VMC-Lab-Chen** [comment]
感谢答复！祝科研顺利，生活愉快！
