### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by Ian0926** [yanzq95/SGNet#15]
Thanks for your great work. NYU data contains 2,000 training images. Are only the first 1,000 images used for training in your work?

**Comment by yanzq95** [comment]
The NYU dataset contains 1,000 pairs of RGB-D for training and 449 pairs for testing. In this paper, we use the training dataset preprocessed by DKN, where each image (480×640) is evenly divided into **TWO** (480×320) images along the width dimension. Therefore, there are 2,000 pairs of RGB-D included in "train_xxx.npy" in total.

**Comment by Ian0926** [comment]
Thanks for your response.
