### ISSUE TITLE
asking code issues

### ISSUE THREAD

**Issue by anan1024** [yanzq95/SGNet#2]
您好，您的thops 是自己编写的吗？
![1](https://github.com/yanzq95/SGNet/assets/75205038/0bbced76-620d-4ada-8429-ca66fc7b46c9)

**Comment by yanzq95** [comment]
你好，这是现成的包，执行 pip install thop==0.1.1.post2209072238

**Comment by anan1024** [comment]
好的好的，谢谢您，按照您的方法，thop的问题已经解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhiqiang ***@***.***&gt;; 
发送时间: 2023年12月15日(星期五) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yanzq95/SGNet] asking code issues (Issue #2)





 
你好，这是现成的包，执行 pip install thop==0.1.1.post2209072238

**Comment by anan1024** [comment]
你好，之前的问题，是我修改的问题  我把import thops  改成import thop as thops  但现在我根据您的方法，仍然无法识别thops
![333](https://github.com/yanzq95/SGNet/assets/75205038/dfd4e826-6686-44ac-b1fa-6d5fb9cdc738)

**Comment by yanzq95** [comment]
> 你好，之前的问题，是我修改的问题 我把import thops 改成import thop as thops 但现在我根据您的方法，仍然无法识别thops ![333](https://private-user-images.githubusercontent.com/75205038/291792383-dfd4e826-6686-44ac-b1fa-6d5fb9cdc738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjQyNDUsIm5iZiI6MTcwMzA2Mzk0NSwicGF0aCI6Ii83NTIwNTAzOC8yOTE3OTIzODMtZGZkNGU4MjYtNjY4Ni00NGFjLWIxZmEtNmQ1ZmI5Y2RjNzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWI2ZjVjMGU3YTFjNGIwYTM5MmNmZGY5NjcxYTdkN2I5N2IyNDhmZDdhOTAxYTE0YWIyYzczMzFiNDAwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCfTeqq-8UW-UQp-SopSAf8OrOyqYmXI86EzfgrsmLw)

非常抱歉，我们检查之后发现thop.py是一个单独的文件，已经上传，谢谢~

**Comment by anan1024** [comment]
好的好的，感谢您的分享。
