### ISSUE TITLE
一些文件的问题

### ISSUE THREAD

**Issue by anan1024** [yanzq95/SGNet#4]
您好，您图中的文件方便分享一下吗？ 我在dataset中放置的是NYU-v2的数据集，不知道test_minmax 中应该放什么。如不方便的话，您能告诉一下，应该放入什么文件吗？  

![11](https://github.com/yanzq95/SGNet/assets/75205038/bfe7e9fd-4c48-4c8b-87c6-ce40d243be1a)

![22](https://github.com/yanzq95/SGNet/assets/75205038/40dfc721-1006-4ff2-825b-c15cd9fc4011)

**Comment by yanzq95** [comment]
NYUv2 dataset and the ''test_minmax.npy'' can be found in issue #1 .

**Comment by anan1024** [comment]
好的好的，谢谢你的回答。
