### ISSUE TITLE
Custom data and Custom Training

### ISSUE THREAD

**Issue by gkuberreddy** [yanzq95/SGNet#5]
Hi,
     Thanks for your great work. I was wondering if you any comments/ code for these points below:

1. **Custom data preprocessing**: I wanted to know how did you come up with npy files for train and test for both RGB and Depth splits? Can you please share the preprocessing code for the same with some clear instructions?
2. **Custom Training**: If we have to custom train on our own datasets, how do we come up with the files for training from custom data? 
3. **Visualization**: It looks like visualization code is missing in the current repo. Can you please let me know how can I get access to the visualization code?

Looking forward to your help and thanks in advance.

Best.

**Comment by yanzq95** [comment]
The npy files are only used in NYUv2 dataset, provided by DKN. Thus, we do not have the processing code. 

But don't worry! The npy files just aim to save the maximums and minimums of depth maps, for **normalization**. If you need to train on your own datasets, please refer to https://github.com/yanzq95/SGNet/blob/7830cf7d2dba83f6d6f0e20f3b8973d0bcdc2cbd/data/rgbdd_dataloader.py#L106. Feel free to build your own dataloader based on the the _rgbdd_dataloader.py_ file.

In several days, we will update the train.py and test.py for all datasets, and add the codes of saving depth & visualization in test.py. 

Thanks for your valuable comments!

**Comment by gkuberreddy** [comment]
> The npy files are only used in NYUv2 dataset, provided by DKN. Thus, we do not have the processing code.
> 
> But don't worry! The npy files just aim to save the maximums and minimums of depth maps, for **normalization**. If you need to train on your own datasets, please refer to
> 
> https://github.com/yanzq95/SGNet/blob/7830cf7d2dba83f6d6f0e20f3b8973d0bcdc2cbd/data/rgbdd_dataloader.py#L106
> 
> . Feel free to build your own dataloader based on the the _rgbdd_dataloader.py_ file.
> In several days, we will update the train.py and test.py for all datasets, and add the codes of saving depth & visualization in test.py.
> 
> Thanks for your valuable comments!

Thank you @yanzq95  for the response. I look forward to any additional code you can provide.

**Comment by yanzq95** [comment]
Visualization code:
https://github.com/yanzq95/SGNet/blob/0aba40f0214898dd841cbbddf0d267ea473d6841/test.py#L133
