### ISSUE TITLE
作者您好，请问是否方便提供可视化的代码？

### ISSUE THREAD

**Issue by KiZemmy** [yanzq95/SGNet#7]

**Comment by yanzq95** [comment]
1个channel的预测结果的可视化代码可参考：
https://github.com/yanzq95/SGNet/blob/0aba40f0214898dd841cbbddf0d267ea473d6841/test.py#L133
n个channel的中间特征可视化代码类似，以通道循环即可保存，例如 for single_channel in channels: ...

特征的颜色选择可使用matplotlib.pyplot的cmap参数,  等等

**Comment by KiZemmy** [comment]
> 1个channel的预测结果的可视化代码可参考：
> 
> https://github.com/yanzq95/SGNet/blob/0aba40f0214898dd841cbbddf0d267ea473d6841/test.py#L133
> 
> 
> n个channel的中间特征可视化代码类似，以通道循环即可保存，例如 for single_channel in channels: ...
> 特征的颜色选择可使用matplotlib.pyplot的cmap参数, 等等

感谢！祝您生活愉快
